name: Docker Image Build and Deploy
on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcv-server
      IMAGE_TAG: latest
      DOCKER_TARGET_PATH: ./server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_TARGET_PATH }}
          file: ${{ env.DOCKER_TARGET_PATH }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
